steps:
- name: 'docker.io/library/python:3.7'
  id: INSTALL_THEN_RUN_TESTS
  entrypoint: /bin/sh
  args: [-c, 'pip install -r requirements.txt', '&&', 'python -m unittest discover']
- name: 'gcr.io/cloud-builders/docker'
  id: BUILD
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/rental_housing_scraper', '.']
  waitFor: ['INSTALL_THEN_RUN_TESTS']